main:
  steps:
    - init:
        assign:
          - execution_results: {}
          - execution_results.success: {}
          - execution_results.exception: {}
    - resolve:
        try:
          steps:
              - call_resolve_forecasts:
                  call: http.post
                  args:
                      url: https://SUBDOMAIN.cloudfunctions.net/resolve_forecasts
                      auth:
                           type: OIDC
                      timeout: 1800
                  result: api_response_resolve
              - save_successful_resolve:
                  assign:
                    - execution_results.success["resolve"]: True
        retry: ${http.default_retry}
        except:
          as: e
          steps:
              - save_failed_resolve:
                  assign:
                    - execution_results.failure: True
                    - execution_results.success["resolve"]: False
                    - execution_results.exception["resolve"]: ${e}
              - raise_resolve_exception:
                  raise: ${execution_results}
    - leaderboard:
        try:
          steps:
              - call_leaderboard:
                  call: http.post
                  args:
                      url: https://SUBDOMAIN.cloudfunctions.net/leaderboard
                      auth:
                           type: OIDC
                      timeout: 1800
                  result: api_response_leaderboard
              - save_successful_leaderboard:
                  assign:
                    - execution_results.success["leaderboard"]: True
        retry: ${http.default_retry}
        except:
          as: e
          steps:
              - save_failed_leaderboard:
                  assign:
                    - execution_results.failure: True
                    - execution_results.success["leaderboard"]: False
                    - execution_results.exception["leaderboard"]: ${e}
              - raise_leaderboard_exception:
                  raise: ${execution_results}
    - check_exception_encountered:
        switch:
          - condition: ${"failure" in execution_results}
            steps:
              - raise_exception:
                  raise: ${execution_results}
    - return_execution_results:
        return: ${execution_results}
